### ISSUE TITLE
Fix issue with mac / safari

### ISSUE THREAD

**Issue by yfalcone** [runtimeverification/ercx-vscode#12]
We seem to have a problem with the plugin when run either on Safari or on mac.
No tests are generated.

Illustrative screenshot attached.

[Capture d’écran 2023-10-16 à 10.53.14.pdf](https://github.com/runtimeverification/ercx-vscode/files/12914218/Capture.d.ecran.2023-10-16.a.10.53.14.pdf)

**Comment by radumereuta** [comment]
Tested on @anvacaru M1, ventura OS 13.1, Safari v16.2
Local VSCode works as expected.
In safari github.dev wouldn't even load.

**Comment by jinxinglim** [comment]
I am closing this as I think this is being addressed.
