### ISSUE TITLE
Code lens is displayed also before log emission

### ISSUE THREAD

**Issue by yfalcone** [runtimeverification/ercx-vscode#14]
The code lens is supposed to display only on the top of the class.
But it seems to display also randomly before some log emissions line of code.
[Capture d’écran 2023-10-16 à 12.12.48.pdf](https://github.com/runtimeverification/ercx-vscode/files/12914997/Capture.d.ecran.2023-10-16.a.12.12.48.pdf)

**Comment by radumereuta** [comment]
Currently, I use a regex to detect the location of where a contract lies.
To fix it properly we need to parse the file and find the location of contracts.

We should consider not adding this to test files if we detect the filename to be something like `*.t.sol` and/or are in a folder named `test` in a foundry project.
