### ISSUE TITLE
Add an option to add the API key

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/ercx-vscode#17]
- add an option in the extension where to place the API key
- send the key in the header under 'X-API-KEY'
@yiyi-wang-rv what should I do if there is no API key? Should I send blank, or not include this at all?

**Comment by yiyi-wang-rv** [comment]
If there is no API key then we don't set `X-API-KEY` in the header.  

Below is an code example:

```typescript
fetch('https://ercx.runtimeverification.com/api/v1/user', {
  headers: {
    'X-API-KEY': 'xxxxxx'
  }
})
```
