### ISSUE TITLE
Tests disappearing and not reappearing

### ISSUE THREAD

**Issue by yfalcone** [runtimeverification/ercx-vscode#7]
If I click on `Hide tests`, tests disappear.
Then, if I click on the code lens, tests do not reappear.

**Comment by radumereuta** [comment]
This is actually how VSCode works.
If you choose to hide some tests, then they will be hidden from view. They are still on the list, but they are not shown by default.
You can click on `Show hidden tests`, and then you can see the list again.
You can select the ERCx tests and click on `Unhide Tests` and you are back to normal.

I can't find a way to unhide the tests programmatically so I'm closing this issue with no further action.
