### ISSUE TITLE
Tests appear as still running even after closing and reopening VSCode

### ISSUE THREAD

**Issue by yfalcone** [runtimeverification/ercx-vscode#8]
Tests seem to be still running even after closing and reopening VSCode.

The attached screenshot shows the state after closing VSCode and reopening.
[Capture d’écran 2023-10-13 à 18.52.35.pdf](https://github.com/runtimeverification/ercx-vscode/files/12895744/Capture.d.ecran.2023-10-13.a.18.52.35.pdf)

**Comment by radumereuta** [comment]
@yfalcone I don't see from the screenshot how tests are running. The testing list is empty.

The test results are persistent.
![image](https://github.com/runtimeverification/ercx-vscode/assets/5113255/3784371b-333f-47a5-8a88-5fae055be275)
If you look at the `Test Results` tab, you can see the previous runs and their results. You can clear the results after a run and get back to the original state.

**Comment by jinxinglim** [comment]
Closing this as no one is working on it.
